@CommentSystem.WebApi_HostAddress = http://localhost:5077

GET {{CommentSystem.WebApi_HostAddress}}/api/posts/1
Accept: application/json

###

GET {{CommentSystem.WebApi_HostAddress}}/api/posts/1/comments?limit=20
Accept: application/json

###

POST {{CommentSystem.WebApi_HostAddress}}/api/posts/1/comments
Content-Type: application/json

{ "content": "have a good day" }

###
